spring:
  application:
    name: "Accounting Service"

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
      base-path: "/"
      path-mapping:
        prometheus: "metrics"
  metrics:
    tags:
      application: accounting-service

server:
  port: 8081